/**
 * Builder data sourced from content-manifest.ts (generated by prebuild script).
 * No fs/glob at runtime — safe for Cloudflare Workers.
 */
import matter from "gray-matter";
import { BUILDER_RAW } from "./content-manifest";

export type BuilderMeta = {
  slug: string;
  title: string;
  builder: string;
  rating: number;
  address: {
    street: string;
    city: string;
    province: string;
    postal: string;
  };
  pros: string[];
  cons: string[];
  status: "failed" | "terminated" | "success";
  possession_date: string | null;
};

function parseBuilder(slug: string, raw: string): { meta: BuilderMeta; content: string } {
  const { data, content } = matter(raw);
  return {
    meta: {
      slug,
      title: data.title || slug,
      builder: data.builder || slug,
      rating: data.rating || 0,
      address: data.address || { street: "", city: "", province: "", postal: "" },
      pros: data.pros || [],
      cons: data.cons || [],
      status: data.status || "failed",
      possession_date: data.possession_date || null,
    },
    content,
  };
}

export async function getAllBuilders(): Promise<{ meta: BuilderMeta; content: string }[]> {
  return Object.entries(BUILDER_RAW).map(([slug, raw]) => parseBuilder(slug, raw));
}

export async function getBuilderBySlug(
  slug: string
): Promise<{ meta: BuilderMeta; content: string } | null> {
  const raw = BUILDER_RAW[slug];
  if (!raw) return null;
  return parseBuilder(slug, raw);
}
