/**
 * Post data sourced from content-manifest.ts (generated by prebuild script).
 * No fs/glob at runtime — safe for Cloudflare Workers.
 */
import matter from "gray-matter";
import { POST_RAW } from "./content-manifest";

export type PostMeta = {
  slug: string;
  title: string;
  date: string;
  description: string;
  tags: string[];
  builder?: string;
  draft: boolean;
  year: string;
  month: string;
  day: string;
  filePath: string;
};

function parseFilename(filename: string): { year: string; month: string; day: string; slug: string } {
  const match = filename.match(/^(\d{4})-(\d{2})-(\d{2})-(.+)$/);
  if (!match) throw new Error(`Invalid filename: ${filename}`);
  return { year: match[1], month: match[2], day: match[3], slug: match[4] };
}

function parsePost(key: string, raw: string): PostMeta {
  // key format: "subdir/2024-11-10-some-slug"
  const [subdir, filename] = key.split("/");
  const { year, month, day, slug } = parseFilename(filename);
  const { data } = matter(raw);
  return {
    slug,
    title: data.title || slug,
    date: data.date ? new Date(data.date).toISOString() : "",
    description: data.description || "",
    tags: data.tags || [],
    builder: data.builder,
    draft: data.draft ?? false,
    year,
    month,
    day,
    filePath: `${subdir}/${filename}.mdx`,
  };
}

export async function getAllPosts(): Promise<PostMeta[]> {
  return Object.entries(POST_RAW)
    .map(([key, raw]) => parsePost(key, raw))
    .filter((p) => !p.draft)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export async function getPostBySlug(
  year: string,
  month: string,
  day: string,
  slug: string
): Promise<{ meta: PostMeta; content: string } | null> {
  const entry = Object.entries(POST_RAW).find(([key]) => {
    const [, filename] = key.split("/");
    const parsed = parseFilename(filename);
    return parsed.year === year && parsed.month === month && parsed.day === day && parsed.slug === slug;
  });
  if (!entry) return null;
  const [key, raw] = entry;
  const { content } = matter(raw);
  return { meta: parsePost(key, raw), content };
}
