timeline
    section initial searching
    section travel
    section active negotiation
        Nov 2: Drop off deposit with Trish
             : Requested sample terms (void contract) to review [denied]
        Nov 12: Went in to sign the contract
              : Provided ID with full legal name
        Nov 13: Finally recieved a contract
        Nov 14: Provided notice that my name is incorrect on the documents
        Nov 20: Provide non-waiver
    section conditional contract
