name: Deploy Jekyll site to Cloudflare Pages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: cloudflare
      url: ${{steps.deploy.outputs.deployment-url}}
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Build Jekyll site
        run: ./bin/build.sh
      - name: Publish to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@7a5f8bbdfeedcde38e6777a50fe685f89259d4ca
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 62758afcaaf5e929beeac70e72312bc6
          wranglerVersion: "3"
          command: pages deploy _site --project-name lanark-house --commit-dirty=true